EarTube/Controllers/SongController.cs
using EarTube.Areas.Identity.Data;
using EarTube.Helpers;
using EarTube.Models;
using EarTube.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EarTube.Controllers
{
    public class SongController : Controller
    {
        private readonly ISongRepository _songRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public SongController(ISongRepository songRepository,
            IWebHostEnvironment webHostEnvironment,
            UserManager<ApplicationUser> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _songRepository = songRepository;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<ViewResult> GetAllSongs(bool isSuccess, int? songId)

        {
            //var userId = _userManager.GetUserId(this.HttpContext.User);
            var datas = await _songRepository.GetAllSongs();

            ViewBag.IsSuccess = TempData["Alert"];
            ViewBag.SongId = TempData["SongID"];
            //isSuccess = false;
            TempData["Alert"] = false;
            TempData["SongID"] = 0;

            foreach (var data in datas)
            {
                data.CalculateTime = _songRepository.CalculateTime(data.CreatedOn.GetValueOrDefault());
            }

            return View(datas);
            //return RedirectToAction(datas, new { isSuccess = true, songId = datas.Count() });
        }


        //Get Song by UserId
        [Authorize]
        public async Task<IActionResult> GetSongByUser(/*bool isSuccess, int songId*/)

        {
            var userId = _userManager.GetUserId(this.HttpContext.User);
            var datas = await _songRepository.GetSongByUser(userId);


            if (datas.Count < 0)
                return RedirectToAction(nameof(GetAllSongs));


            return View(datas);
            //return RedirectToAction(datas, new { isSuccess = true, songId = datas.Count() });
        }

        [Authorize]
        //Get User Account 
        [Route("user-account/{accountUserId}", Name = "getUserAccount")]
        public async Task<IActionResult> GetUserAccount(string accountUserId)
        {
            //var userId = _userManager.GetUserId(this.HttpContext.User);
            var datas = await _songRepository.GetSongByUser(accountUserId);
            ViewBag.IsSubscribe = await CheckSubscribeString(accountUserId);
            if (datas.Count < 0)
                return RedirectToAction(nameof(GetAllSongs));


            return View(datas);
            //return RedirectToAction(datas, new { isSuccess = true, songId = datas.Count() });
        }

        [Authorize]
        // Get - AddNewSong
        public ViewResult AddNewSong(/*bool isSuccess = false, int songId = 0*/)
        {
            var model = new SongModel();
            //ViewBag.IsSuccess = isSuccess;
            //ViewBag.SongId = songId;
            return View(model);
        }
        [Authorize]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> AddNewSong(SongModel songModel, bool isSuccess = false, int songId = 0)
        {
            var userId = _userManager.GetUserId(this.HttpContext.User);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            songModel.UserId = userId;
            if (ModelState.IsValid)
            {
                if (songModel.CoverPhoto != null)
                {
                    string folder = "songs/cover/";
                    songModel.CoverImageUrl = await UploadImage(folder, songModel.CoverPhoto);
                }

                if (songModel.SongFile != null)
                {
                    string folder = "songs/songfiles/";
                    songModel.SongUrl = await UploadImage(folder, songModel.SongFile);
                }

                ViewBag.IsSuccess = isSuccess;
                ViewBag.SongId = songId;

                int id = await _songRepository.AddNewSong(songModel);
                if (id > 0)
                {
                    //return RedirectToAction(nameof(AddNewSong), new { isSuccess = true, songId = id });
                    TempData["Alert"] = true;

                    // Mail sending

                    //#region Mail

                    MailMessage msg = new MailMessage  // instance Mail sender service
                    {
                        From = new MailAddress("asamoja9123@gmail.com"),  // Server Email Address
                    };

                    var subscribers = _songRepository.GetSubscriber(userId);
                    foreach (var subscriber in subscribers)
                    {
                        msg.To.Add(subscriber.SubscribeUserEmail); // receiver Email

                        msg.Subject = "EarTube - New Song Upload";
                        msg.Body = $"Hello {subscriber.SubscribeUserEmail}, {user.FirstName}-{user.LastName}  as added a new song. Go check it out";  // Message Body
                    }


                    SmtpClient client = new SmtpClient
                    {
                        Host = "smtp.gmail.com"
                    };
                    NetworkCredential credential = new NetworkCredential
                    {  // Server Email credentisal
                        UserName = "asamoja9123@gmail.com",
                        Password = "asaVault9123!"
                    };
                    client.Credentials = credential;
                    client.EnableSsl = true;
                    client.Port = 587;
                    client.Send(msg);


                    ViewBag.Success = $"Email has been sent successfully to your subscriber";
                    return RedirectToAction(nameof(GetAllSongs), new { songId = id });
                }
            }

            return View();
        }

        [Authorize]
        //AddOrEdit Action Method
        public async Task<IActionResult> AddOrEdit(int? songId = 0, bool isSuccess = false)
        {
            if (songId == 0)
            {
                var model = new SongModel();
                return View(model);
            }
            else
            {
                ViewBag.IsSuccess = isSuccess;
                ViewBag.SongId = songId;
                if (songId == null)
                {
                    return NotFound();
                }
                var data = await _songRepository.GetSongById(songId);
                if (data == null)
                {
                    return NotFound();
                }
                return View(data);
            }
        }

        //Post AddOrEdit/id
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(SongModel songModel, bool isSuccess = false, int songId = 0)
        {
            if (songModel.Id == 0)
            {
                var userId = _userManager.GetUserId(this.HttpContext.User);
                var user = await _userManager.GetUserAsync(HttpContext.User);
                songModel.UserId = userId;
                if (ModelState.IsValid)
                {
                    if (songModel.CoverPhoto != null)
                    {
                        string folder = "songs/cover/";
                        songModel.CoverImageUrl = await UploadImage(folder, songModel.CoverPhoto);
                    }

                    if (songModel.SongFile != null)
                    {
                        string folder = "songs/songfiles/";
                        songModel.SongUrl = await UploadImage(folder, songModel.SongFile);
                    }
                    int id = await _songRepository.AddNewSong(songModel);
                    if (id > 0)
                    {
                        TempData["Alert"] = true;
                        TempData["SongID"] = id;

                    }

                    // Mail sending

                    //#region Mail

                    MailMessage msg = new MailMessage  // instance Mail sender service
                    {
                        From = new MailAddress("asamoja9123@gmail.com"),  // Server Email Address
                    };

                    var subscribers = _songRepository.GetSubscriber(userId);
                    if (subscribers.Count() > 0)
                    {
                        foreach (var subscriber in subscribers)
                        {
                            msg.To.Add(subscriber.SubscribeUserEmail); // receiver Email

                            msg.Subject = "EarTube - New Song Upload";
                            msg.Body = $"Hello {subscriber.SubscriberFirstName} {subscriber.SubscriberLastName}, {user.FirstName}-{user.LastName}  as added a new song. Go check it out";  // Message Body
                        }
                        SmtpClient client = new SmtpClient
                        {
                            Host = "smtp.gmail.com"
                        };
                        NetworkCredential credential = new NetworkCredential
                        {  // Server Email credentisal
                            UserName = "asamoja9123@gmail.com",
                            Password = "asaVault9123!"
                        };
                        client.Credentials = credential;
                        client.EnableSsl = true;
                        client.Port = 587;

EarTube/ViewComponents/CurrentUserViewComponent.cs
using EarTube.Areas.Identity.Data;
using EarTube.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EarTube.ViewComponents
{
    public class CurrentUserViewComponent :ViewComponent
    {
        private readonly ApplicationDbContext _db;

        public CurrentUserViewComponent(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var userDb = await _db.Users.FirstOrDefaultAsync(u => u.Id == claims.Value);

            return View(userDb);
        }
    }
}

EarTube/ViewComponents/MostViewSongViewComponent.cs
using EarTube.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EarTube.ViewComponents
{
    public class MostViewSongViewComponent :ViewComponent
    {
        private readonly SongRepository _repo;

        public MostViewSongViewComponent(SongRepository repo)
        {
            _repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var mostView = await _repo.HotSongs();

            foreach (var data in mostView)
            {
                data.CalculateTime = _repo.CalculateTime(data.CreatedOn.GetValueOrDefault());
            }
            return View(mostView);
        }
    }
}

EarTube/Views/Song/AddNewSong.cshtml
@model SongModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-md-10">
            <h3 class="display-4">Upload new Song</h3>
            <hr />
            @*@if (ViewBag.IsSuccess == true)
            {
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Congratulations</strong> You have added new song successfully. <br />
                    Click <a asp-controller="Song" asp-action="GetSong" asp-route-id="@ViewBag.songId">here</a> to view the details
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }*@

            <form method="post" enctype="multipart/form-data" asp-action="AddNewSong" asp-controller="Song">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Artist" class="control-label"></label>
                            <input asp-for="Artist" class="form-control" />
                            <span asp-validation-for="Artist" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Genre" class="control-label"></label>
                            <input asp-for="Genre" class="form-control" />
                            <span asp-validation-for="Genre" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="CoverPhoto" class="control-label"></label>
                            <div class="custom-file">
                                <input asp-for="CoverPhoto" class="custom-file-input" id="customFile">
                                <label class="custom-file-label text-dark" for="customFile">Choose file</label>
                            </div>
                            <span asp-validation-for="CoverPhoto" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="SongFile" class="control-label"></label>
                            <div class="custom-file">
                                <input asp-for="SongFile" class="custom-file-input" id="validatedCustomFile" required>
                                <label class="custom-file-label text-dark" for="validatedCustomFile">Choose file</label>
                            </div>
                            <span asp-validation-for="SongFile" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                @*<div class="form-group">
                    <label asp-for="Comment" class="control-label"></label>
                    <textarea asp-for="Comment" class="form-control"></textarea>
                    <span asp-validation-for="Comment" class="text-danger"></span>
                </div>*@

                <div class="form-group">
                    <input type="submit" value="Upload" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

EarTube/Views/Song/GetAllSongs.cshtml
@model IEnumerable<SongModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="notify-upload">
        
    </div>

    <div class="">
        <h3 class="h5 text-uppercase">All Songs</h3>
        <br />
        <div>
            @if (ViewBag.IsSuccess == true)
            {
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    You have added a new <strong>song</strong> successfully. <br />
                    Email successfully sent to your subscribers.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
        </div>

        @if (Model.Count() > 0)
        {

            <div class="row col-md-12" id="view-all">
                @* Inserted Partial view all *@
                @await Html.PartialAsync("_ViewAll", Model)
                @*<partial name="_ViewAll" model="Model" />*@
            </div>
        }
        else
        {
            <p>No songs</p>
        }
    </div>



@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

EarTube/Views/Song/GetSong.cshtml
@*@model EarTube.ViewModel.SongCommentViewModel*@
@model SongModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@*@model Comment*@
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12" style="background-color:#0a0a0a;">
    <h5 class="h5 text-uppercase">Song details</h5>
    <br />
    <div>
        @if (ViewBag.IsSuccess == true)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Congratulations</strong> You have added a new comment successfully. <br />
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }

        @if (ViewBag.IsLikeSuccess == true)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                You already <strong>Like</strong> this song <br />
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }

        @if (ViewBag.LikeSuccess == true)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                You <strong>Like</strong> this song <br />
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }




        @* Dislike Alert *@
        @if (ViewBag.IsDislikeSuccess == true)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                You already <strong>Dislike</strong> this song <br />
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }

        @if (ViewBag.DislikeSuccess == true)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                You <strong>Dislike</strong> this song <br />
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        <div class="row col-12">
            <div class="col-md-8">

                <div class="row">
                    <div class="col-md-12">
                        <img src="@(string.IsNullOrEmpty(Model.CoverImageUrl) ? "/images/unsplash.jpg": Model.CoverImageUrl)" class="img-thumbnail" style="width: 740px; height: 420px; left: 0px; top: 0px;" />
                        <div id="audio player testing">
                            <div class="card-block">
                                <div class="mp3-audio">
                                    <audio controls class="mp3-audio">
                                        <source src="@(string.IsNullOrEmpty(Model.SongUrl) ? "/images/unsplash.mp3": Model.SongUrl)" type="audio/mpeg">
                                        <source src="audio/lp_78_am_guitar_funk_reggae.mp3" type="audio/mpeg">
                                        <source src="audio/lp_78_am_guitar_funk_reggae.ogg" type="audio/ogg">
                                        <source src="audio/lp_78_am_guitar_funk_reggae.wav" type="audio/wav">
                                        Your browser does not support the audio element.
                                    </audio>
                                </div>
                            </div>
                        </div>
                        <h5 class="text-capitalize my-2 pl-4"><span>@Model.Title</span></h5>
                        <div class="row col-12 mt-3">
                            <div class="col-md-3 py-2 small pl-2 ">
                                <span class=" text-muted">@Model?.SongView.ToString() Views . </span>
                                <span class=" text-muted">@((Model.CreatedOn.HasValue)? Model.CreatedOn.Value.ToShortDateString().ToString(): "No Date" ) </span>
                            </div>
                            <div class="col-md-2 ">
                                <a data-toggle="tooltip" data-placement="bottom" title="Download"
                                   class="btn btn-outline-primary p-2@((UserManager.GetUserId(User).ToString() != Model.UserId)? " ": " d-none") small" href="@Model.SongUrl" target="_blank" download="EarTube-@Model.Id">
                                    Download
                                </a>
                            </div>

                            <div class="col-md-7 p-0 py-1">

                                @if (UserManager.GetUserId(User).ToString() == Model.UserId)
                                {
                                    <div class="btn-group">
                                        @*<a asp-route="editSong" asp-route-id="@Model.Id"*@
                                        @*<a asp-controller="Song" asp-action="AddOrEdit" asp-route-songId="@Model.Id"*@
                                        <a data-toggle="tooltip" data-placement="bottom" title="Edit"
                                           onclick="showInPopup('@Url.Action("AddOrEdit","Song",new { songId = Model.Id},Context.Request.Scheme)','Edit Song Upload')"
                                           class="btn btn-sm btn-outline-primary"><i class="fas fa-edit"></i></a>
                                    </div>
                                    <div class="btn-group" data-toggle="tooltip" data-placement="bottom" title="Delete">
                                        <a asp-route="deleteSong" asp-route-id="@Model.Id"
                                           class="btn btn-sm btn-outline-primary"><i class="fas fa-trash"></i></a>
                                    </div>
                                }

                                <span id="buttons">
                                    <span class="text-muted AjaxLike" data-toggle="tooltip" data-placement="bottom" title="I like this">
                                        <a asp-route="youtubeLikeSong" asp-route-id="@Model.Id"
                                           data-ajax="true" data-ajax-success="AjaxLike"
                                           class="pl-1"><i class="fas fa-thumbs-up fa-6"><span class="px-2  ">@Model.SongLike.ToString()</span></i></a>
                                    </span>

                                    <span class="text-muted AjaxDislike" data-toggle="tooltip" data-placement="bottom" title="I dislike this">
                                        <a asp-route="youtubeDislikeSong" asp-route-id="@Model.Id"
                                           data-ajax="true" data-ajax-success="AjaxDislike"
                                           class="pl-1 @((UserManager.GetUserId(User).ToString() != Model.UserId)? " ": "btn disabled")"><i class="fas fa-thumbs-down fa-6"><span class="px-2">@Model.SongDisLike.ToString()</span></i></a>
                                    </span>

                                    <span class="text-muted">
                                        <a asp-route="shareSong" asp-route-id="@Model.Id"
                                           class="px-1"><i class="fas fa-share fa-6"></i></a>
                                    </span>
                                </span>
                                <span id="info" class="">
                                    <small class="text-light bg-primary p-1">@(string.IsNullOrEmpty(Model.Genre) ? "Genre: NA" : Model.Genre)</small>
                                    <small class="text-light bg-primary p-1 ml-1">@(string.IsNullOrEmpty(Model.Artist) ? "NA" : Model.Artist)</small>
                                </span>
                                @*<small class="text-light bg-primary p-1">@(string.IsNullOrEmpty(Model.Like) ? "No Likes" : "Likes : " + Model.Like)</small>*@
                            </div>
                        </div>
                    </div>

                </div>
                <hr />
                <div class="border-top"></div>

                <div class="row ">
                    <div class="row p-4 col-md-12 d-flex  align-items-center">
                        <div class="col-md-1 ml-1">
                            <a asp-route="getUserAccount" asp-route-accountUserId="@((Model.User == null) ? "null" : Model.User.Id)">
                                <img src="@(string.IsNullOrEmpty(Model?.User?.UserImageUrl) ? "/images/Avatar.png" : Model.User.UserImageUrl)" class="img-fluid" style="border-radius:50%; width: 36px; height: 36px;" />
                            </a>
                        </div>
                        <div class="col-md-9">
                            <a asp-route="getUserAccount" asp-route-accountUserId="@((Model.User == null) ? "null" : Model.User.Id)">
                                <span class="d-block text-capitalize">@((Model.User != null) ? Model.User.FirstName + " " + Model.User.LastName : "No Account User")</span>
                            </a>
                            <span class="d-block text-capitalize">@((Model.User != null && Model.User.Subscriber > 0) ? Model.User.Subscriber.ToString() + " Subscribers" : "No Subscriber"  ) </span>
                        </div>
                        <div class="col-md-1">
                            @*<a
        id="subscribeButton"
        asp-route="subscribe" asp-route-id="@Model.Id"
        data-ajax="true" data-ajax-success="AjaxSuccess" data-ajax-complete="AjaxComplete"
        class="btn btn-danger subscribeButton">Subscribe</a>*@
                            @if (ViewBag.IsSubscribe)
                            {
                                <a id="subscribeButton"
                                   asp-route="subscribe" asp-route-id="@Model.Id"
                                   data-ajax="true" data-ajax-success="AjaxSuccess" data-ajax-complete="AjaxComplete"
                                   class="btn  btn-secondary subscribeButton">
                                    Unsubscribe
                                </a>
                            }
                            else
                            {
                                <a id="subscribeButton"
                                   asp-route="subscribe" asp-route-id="@Model.Id"
                                   data-ajax="true" data-ajax-success="AjaxSuccess" data-ajax-complete="AjaxComplete"
                                   class="btn btn-danger subscribeButton">
                                    Subscribe
                                </a>
                            }
                        </div>
                    </div>
                    <div class="row col-md-10 offset-1">
                        <p class="more">@Model.Description</p>
                    </div>
                </div>

                <div class="border-top"></div>
                <div class="row  col-md-12 d-flex  align-items-center">
                    <div class="col-md-1">
                        @* Login User *@
                        @await Component.InvokeAsync("CurrentUser")
                    </div>
                    <div class="col-md-10">
                        <div class="my-3">
                            <div class="btn-group">
                                @*<a asp-controller="Comment" asp-action="AddComment" asp-route-songId="@Model.Id"*@
                                <a onclick="showInPopup('@Url.Action("AddComment","Comment",new {songId=Model.Id},Context.Request.Scheme)','Add Comment')"
                                   class="btn btn-sm btn-outline-secondary">Click to Comment <i class="fas fa-comment"></i></a>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="border-top mb-4"></div>
                <div class="pl-3">
                    @await Html.PartialAsync("_AddComment", Model)
                </div>
            </div>

            <div class="col-md-4">
                @await Component.InvokeAsync("MostViewSong")
            </div>
            @*<div class="col-md-4 ">
                    <div class="border-top"></div>
                    <p class="my-4">Most Viewed Songs</p>
                    <div class="row">
                        <div class="col-md-6">
                            <img src="~/images/unsplash.jpg " class="img-fluid" style="width:168px; height:94px;"/>
                        </div>
                        <div class="col-md-6">
                            <p>Title</p>
                            <p>UserName</p>
                            <div id="bottom">
                                <span>Views</span>
                                <span>Views</span>
                            </div>
                        </div>
                    </div>
                </div>*@


            @*Buttons*@


        </div>

        <hr />

    </div>


</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

EarTube/Views/Song/GetSongByUser.cshtml
@model IEnumerable<SongModel>
@{
    ViewData["Title"] = "GetSongByUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @if (Model.Count() > 0)
    {

        <div class="row col-md-12" id="view-all">
            @* Inserted Partial view all *@
            @await Html.PartialAsync("_ViewAll", Model)
            @*<partial name="_ViewAll" model="Model" />*@
        </div>
    }
    else
    {
        <p>No songs</p>
    }
</div>